---
title: "A. Villani's microglia RNAseq"
author: "Izaskun Mallona, UZH"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    code_download: true
    number_sections: true
    df_print: kable
    theme: lumen
params:
  seed: 665
---


```{r warning = FALSE, message = FALSE}
## .libPaths('/home/imallona/R/R4_bioc314')

library(ggplot2)
## library(EnhancedVolcano)
## library(iSEE)
## library(knitr)
## library(DRIMSeq)
## library(EnsDb.Hsapiens.v86)
library(SingleCellExperiment)
library(corrplot)
#library(GGally)
#library(scuttle)
#library(knitr)
#library(greybox) # cramer's distance
#library(viridis)
#library(regioneR)
#library(GenomicRanges)
#library(rtracklayer)

## camera start

## library(dplyr)
## library(msigdbr)
## library(CAMERA)

#require(topGO)
#require(org.Hs.eg.db)

## library("ggVennDiagram")
library(recount3)

 library(tibble)
library(dplyr)
##  library(tidyr)
library(limma)
library(edgeR)
library(sva)
## library(reshape2)


```



```{r}
knitr::opts_chunk$set(fig.width = 8,
                      fig.height = 8,
                      cache = TRUE,
                      include = TRUE,
                      fig.path = "plots/",
                      dev = c("png"),
                      cache.lazy = FALSE,
                      warning = TRUE,
                      message = TRUE)

## plan("multiprocess", workers = NTHREADS)
## options(future.globals.maxSize= 1.4e9)

## options(bitmapType='cairo')
```

# Aim

# Data


## Metadata


```{r}
meta <- read.csv(text="treatment,names
iPSC_MG_(Abud),SRR4450428
iPSC_MG_(Abud),SRR4450429
iPSC_MG_(Abud),SRR4450430
iPSC_MG_(Abud),SRR4450431
iPSC_MG_(Abud),SRR4450432
iPSC_MG_(Abud),SRR4450433
iHPC_(Abud),SRR4450434
iHPC_(Abud),SRR4450435
iHPC_(Abud),SRR4450436
iPSC_(Abud),SRR4450437
iPSC_(Abud),SRR4450438
iPSC_(Abud),SRR4450439
iPSC_(Abud),SRR4450440
CD14_M_(Abud),SRR4450441
CD14_M_(Abud),SRR4450442
CD14_M_(Abud),SRR4450443
CD14_M_(Abud),SRR4450444
CD14_M_(Abud),SRR4450445
CD16_M_(Abud),SRR4450446
CD16_M_(Abud),SRR4450447
CD16_M_(Abud),SRR4450448
CD16_M_(Abud),SRR4450449
Fetal_MG_(Abud),SRR4450450
Fetal_MG_(Abud),SRR4450451
Fetal_MG_(Abud),SRR4450452
Adult_MG_(Abud),SRR4450453
Adult_MG_(Abud),SRR4450454
Adult_MG_(Abud),SRR4450455
Blood_DC_(Abud),SRR4450456
Blood_DC_(Abud),SRR4450457
Blood_DC_(Abud),SRR4450458
iPSC_MG_WT_(McQuade),SRR12608405
iPSC_MG_WT_(McQuade),SRR12608406
iPSC_MG_WT_(McQuade),SRR12608407
iPSC_MG_WT_(McQuade),SRR12608408
iPSC_MG_TREM2_KO_(McQuade),SRR12608409
iPSC_MG_TREM2_KO_(McQuade),SRR12608410
iPSC_MG_TREM2_KO_(McQuade),SRR12608411
iPSC_MG_TREM2_KO_(McQuade),SRR12608412
iPSC_MG_2.0_(McQuade),SRR7613924
iPSC_MG_2.0_(McQuade),SRR7613925
iPSC_MG_2.0_(McQuade),SRR7613926
iHPC_2.0_(McQuade),SRR8180288
iHPC_2.0_(McQuade),SRR8180289
iHPC_2.0_(McQuade),SRR8180290,
iPSC_MG,20220209.A-av111_WT_001_R1
iPSC_MG,20220209.A-av111_WT_002_R1
iPSC_MG,20220209.A-av111_WT_003_R1
iPSC_MG,20220209.A-tw029_WT_2_R1
iPSC_MG,20220209.A-tw029_WT_3_R1
iPSC_MG,20220504.B-WTC_1_R1
iPSC_MG,20220504.B-WTC_2_R1
iPSC_MG_Slc37a2_mut1,20220504.B-SLC-EX2B1_1_R1
iPSC_MG_Slc37a2_mut1,20220504.B-SLC-EX2B1_2_R1
iPSC_MG_Slc37a2_mut2,20220504.B-SLC-EX6C5_1_R1
iPSC_MG_Slc37a2_mut2,20220504.B-SLC-EX6C5_2_R1
iPSC_MG_TREM2_mut,20220504.B-TREM2-A1_1_R1
iPSC_MG_TREM2_mut,20220504.B-TREM2-A1_2_R1")
```


## Ambra's

```{r}
d <- readRDS('/home/imallona/avillani_microglia/ambra_only_output/outputR/shiny_sce.rds')$sce_gene
```


```{r}

logcpms <- assay(d, "logcpm")
mds <- limma::plotMDS(logcpms, top = 500, labels = NULL, pch = NULL,
                      cex = 1, dim.plot = c(1, 2), ndim = min(7, ncol(logcpms) - 1),
                      gene.selection = "common",
                      xlab = NULL, ylab = NULL, plot = FALSE)
if (!is.null(mds$cmdscale.out)) {
    ## Bioc 3.12 and earlier
    mds <- mds$cmdscale.out
    colnames(mds) <- paste0("MDS", seq_len(ncol(mds)))
    mds <- as.data.frame(mds) %>% tibble::rownames_to_column(var = "names")
} else {
    mds <- data.frame(names = colnames(logcpms),
                      MDS1 = mds$x,
                      MDS2 = mds$y)
}
mds <- mds %>% 
    dplyr::full_join(data.frame(colData(d)), by = "names")
```

### MDS {.tabset .tabset-pills}

```{r, fig.width = 10, fig.height = 4, results = 'asis'}

for (item in c('treatment', 'timepoint', 'names')) {
    cat('#### ', item, '\n\n')
    print(ggplot(mds, aes(x=MDS1, y=MDS2, color = get(item)), alpha=1) +
          geom_point(size=3) +
          labs(x="Dimension 1", y="Dimension 2", title= paste("MDS", item)) +
          coord_cartesian(xlim=range(mds$MDS1, na.rm=TRUE),
                          ylim=range(mds$MDS2, na.rm=TRUE), expand=TRUE) +
          theme_bw() +
          coord_fixed() + 
          theme(legend.position='right')) #, legend.box='vertical', legend.text=element_text(size=9), legend.title=element_text(size=11),
                #axis.text=element_text(size=10), axis.title=element_text(size=12), title=element_text(size=12)))
    cat('\n\n')

}
```

### Correlation  {.tabset .tabset-pills}

#### All genes

```{r, fig.width = 10, fig.height = 10}
corrplot(cor(logcpms, method= 'spearman'),
         method  =  'circle', type  =  'lower', insig = 'blank',
          number.cex  =  0.8, order  =  'hclust', diag = TRUE , addCoef.col = 'white')


```

#### Top 500 most variable genes

```{r, fig.width = 10, fig.height = 10}
corrplot(cor(logcpms[head(order(rowVars(logcpms), decreasing = TRUE), 500),], method= 'spearman'),
         method  =  'circle', type  =  'lower', insig = 'blank',
         addCoef.col  = 'black', number.cex  =  0.8, order  =  'hclust', diag = TRUE)




```


## Abud {.tabset .tabset-pills}

### Correlations


```{r, message = FALSE, warning = FALSE}
srp <- "SRP092075"
abud <- recount3::create_rse_manual(
                    project = srp,
                    project_home = "data_sources/sra",
                    organism = "human",
                    annotation = "gencode_v29",
                    type = "gene")

assay(abud, "counts") <- transform_counts(abud)


```

```{r, eval = TRUE}
abud <- subset(abud,
               select = colData(abud)$external_id %in%  meta$names)

## abud_annot <- merge(abud_annot, colData(abud), by.x = 'srr', by.y = 'external_id')

```


```{r}
abudlcpm <- edgeR::cpm(assay(abud, 'counts'),
                       log = TRUE, 
                       prior.count = 2)


```

```{r}
## table(rowData(d)$gene_id %in% rowData(abud)$gene_id)

rowData(d)$unversioned_gene_id <- sapply(strsplit(rowData(d)$gene_id, '\\.'), function(x) return(x[[1]]))
rowData(abud)$unversioned_gene_id <- sapply(strsplit(rowData(abud)$gene_id, '\\.'), function(x) return(x[[1]]))

## table(rowData(d)$unversioned_gene_id %in% rowData(abud)$unversioned_gene_id)

shared <- intersect(rowData(d)$unversioned_gene_id, rowData(abud)$unversioned_gene_id)

dict <- data.frame(unversioned_gene_id = shared,
                   ambra = rownames(rowData(d)[rowData(d)$unversioned_gene_id %in% shared,]))

dict <- merge(dict, rowData(abud)[rowData(abud)$unversioned_gene_id %in% shared, c('unversioned_gene_id', 'gene_id')],
              by = 'unversioned_gene_id')
colnames(dict)[3] <- 'recount'
```


```{r, fig.width = 25, fig.height = 25}

## dim(cbind(logcpms[dict$ambra,], abudlcpm[dict$recount,]))

corrplot(cor(cbind(logcpms[dict$ambra,],
                   abudlcpm[dict$recount,]), method= 'spearman'),
         method  =  'circle', type  =  'lower', insig = 'blank',
          number.cex  =  0.8, order  =  'hclust', diag = TRUE , addCoef.col = 'black')
```

### MDS before batch correction

```{r firstmds, fig.width = 8, fig.height = 5}

mds <- limma::plotMDS(cbind(logcpms[dict$ambra,],
                            abudlcpm[dict$recount,]), top = 500, labels = NULL, pch = NULL,
                      cex = 1, dim.plot = c(1, 2), ndim = min(7, ncol(logcpms) - 1),
                      gene.selection = "common",
                      xlab = NULL, ylab = NULL, plot = FALSE)
if (!is.null(mds$cmdscale.out)) {
    ## Bioc 3.12 and earlier
    mds <- mds$cmdscale.out
    colnames(mds) <- paste0("MDS", seq_len(ncol(mds)))
    mds <- as.data.frame(mds) %>% tibble::rownames_to_column(var = "names")
} else {
    mds <- data.frame(names = colnames(cbind(logcpms[dict$ambra,],
                            abudlcpm[dict$recount,])),
                      MDS1 = mds$x,
                      MDS2 = mds$y)
}

mds$origin <- ifelse(grepl('SRR', mds$names), yes = 'Abud', no = 'Ambra')

mds <- na.omit( mds %>% dplyr::full_join(data.frame(meta), by = "names"))

```

```{r, fig.width = 10, fig.height = 4, results = 'asis'}

print(ggplot(mds, aes(x=MDS1, y=MDS2, color = origin), alpha=1) +
      geom_point(size=3) +
      labs(x="Dimension 1", y="Dimension 2", title= paste("MDS before ComBat")) +
      coord_cartesian(xlim=range(mds$MDS1, na.rm=TRUE),
                      ylim=range(mds$MDS2, na.rm=TRUE), expand=TRUE) +
      theme_bw() +
      coord_fixed() + 
      theme(legend.position='right')) #, legend.box='vertical', legend.text=element_text(size=9), legend.title=element_text(size=11),
                                        #axis.text=element_text(size=10), axis.title=element_text(size=12), title=element_text(size=12)))



```

### Batch correction


```{r}
# parametric adjustment
combat_abud <- sva::ComBat(dat=cbind(logcpms[dict$ambra,],
                                    abudlcpm[dict$recount,]),
                          batch = mds$origin,
                          mod = NULL, par.prior = TRUE, prior.plots = TRUE)

```

### MDS after batch, batches


```{r, fig.width = 8, fig.height = 5}
mds <- limma::plotMDS(combat_abud, top = 500, labels = NULL, pch = NULL,
                      cex = 1, dim.plot = c(1, 2), ndim = min(7, ncol(logcpms) - 1),
                      gene.selection = "common",
                      xlab = NULL, ylab = NULL, plot = FALSE)
if (!is.null(mds$cmdscale.out)) {
    ## Bioc 3.12 and earlier
    mds <- mds$cmdscale.out
    colnames(mds) <- paste0("MDS", seq_len(ncol(mds)))
    mds <- as.data.frame(mds) %>% tibble::rownames_to_column(var = "names")
} else {
    mds <- data.frame(names = colnames(cbind(logcpms[dict$ambra,],
                            abudlcpm[dict$recount,])),
                      MDS1 = mds$x,
                      MDS2 = mds$y)
}

mds$origin <- ifelse(grepl('SRR', mds$names), yes = 'Abud', no = 'Ambra')

mds <- na.omit( mds %>% dplyr::full_join(data.frame(meta), by = "names"))

```

```{r, fig.width = 8, fig.height = 4, results = 'asis'}
print(ggplot(mds, aes(x=MDS1, y=MDS2, color = origin), alpha=1) +
      geom_point(size=3) +
      labs(x="Dimension 1", y="Dimension 2", title= paste("MDS after ComBat")) +
      ## coord_cartesian(xlim=range(mds$MDS1, na.rm=TRUE),
      ##                 ylim=range(mds$MDS2, na.rm=TRUE), expand=TRUE) +
      theme_bw() +
      coord_fixed() + 
      theme(legend.position='right')) #, legend.box='vertical', legend.text=element_text(size=9), legend.title=element_text(size=11),
                                        #axis.text=element_text(size=10), axis.title=element_text(size=12), title=element_text(size=12)))
```

### MDS after batch, annotation

```{r, fig.width = 8, fig.height = 4, results = 'asis'}
print(ggplot(mds, aes(x=MDS1, y=MDS2, color = treatment, shape = origin), alpha=1) +
      geom_point(size=3) +
      labs(x="Dimension 1", y="Dimension 2", title= paste("MDS after ComBat")) +
      ## coord_cartesian(xlim=range(mds$MDS1, na.rm=TRUE),
      ##                 ylim=range(mds$MDS2, na.rm=TRUE), expand=TRUE) +
      theme_bw() +
      coord_fixed() + 
      theme(legend.position='right') +
      guides(fill=guide_legend(ncol=2)))

```



```{r}

knitr::knit_exit()
```



## McQuade TREM

```{r}

srp <- 'SRP281230'

trem <- recount3::create_rse_manual(
                    project = srp,
                    project_home = "data_sources/sra",
                    organism = "human",
                    annotation = "gencode_v29",
                    type = "gene")

assay(trem, "counts") <- transform_counts(trem)

```

## McQuade

```{r}
srp <- 'SRP155574'

mc <- recount3::create_rse_manual(
                    project = srp,
                    project_home = "data_sources/sra",
                    organism = "human",
                    annotation = "gencode_v29",
                    type = "gene")

assay(mc, "counts") <- transform_counts(mc)

```


# Procedure


# Timestamp

```{r sessionInfo2, cache = FALSE}
date()
sessionInfo()
devtools::session_info()
```
